# Change it to true to enable the plugin
enable: false

# Set to true to kick the player for using kill aura
kick-player: true

# Message to be shown to the player when they are kicked
kick-message: "You are kicked for using kill aura"

# Set to true to permanently ban the player for using kill aura
ban-player: false

# Message to be shown to the player when they are banned
ban-message: "You are banned for using kill aura"

# Set to true to temporarily ban the player for using kill aura (You will need essentialsX for this to work)
tempban-player: false

# Duration of the temporary ban in seconds
seconds: 1200

# Message to be shown to the player when they are temporarily banned
tempban-message: "You are banned for using kill aura"