name: AdvancedAntiKillAura
version: '${project.version}'
author: "Andreas Karageorgos"
main: plugins.karageorgos.me.advancedAntiKillAura.AdvancedAntiKillAura
api-version: '1.20'
description: A simple kill aura protection
permissions:
  antikillaura.ignore:
    default: op
softdepend:
  - Essentials
